Repository TurboWarp/extensions, pull requests merged in 2025-09, with the labels that each got.

#2240 [Automated] Update translations 2025-09-13
  translations/extension-metadata.json
  translations/extension-runtime.json
Labels: pr: other

#2149 pr: change existing extension New Icon: URL Playback
  images/sound.svg
Labels: pr: other

#2148 HTTP
  images/README.md
  images/godslayerakp/http.svg
Labels: pr: other

#2189 NEW SVG IMAGE FOR LILLY MAKES THINGS HACKED BLOCKS
  images/Lily/HackedBlocks.png
  images/Lily/HackedBlocks.svg
Labels: pr: other

#2036 Add FormatNumbers Extension
  extensions/DogeisCut/FormatNumbers.js
  extensions/extensions.json
  images/DogeisCut/FormatNumbers.png
  images/README.md
Labels: pr: new extension

#2249 godslayerakp/ws: replace default echo server
  extensions/godslayerakp/ws.js
Labels: pr: change existing extension

#2256 godslayerakp/http: clarify blocks that operate on request headers vs response headers
  extensions/godslayerakp/http.js
Labels: pr: change existing extension
