Repository TurboWarp/extensions, pull requests merged in 2025-06, with the labels that each got.

#2143 [Automated] Update translations 2025-06-04
  translations/extension-runtime.json
Labels: pr: other

#2146 Use versions instead of commit hash for official GitHub Actions workflows
  .github/workflows/deploy.yml
  .github/workflows/download-translations.yml
  .github/workflows/format-pr.yml
  .github/workflows/upload-translations.yml
  .github/workflows/validate.yml
Labels: pr: other

#2144 CST1229/images: new image
  images/CST1229/images.svg
  images/README.md
Labels: pr: other

#2152 Xeltalliv/simple3D: mark drawable as non-interactive
  extensions/Xeltalliv/simple3D.js
Labels: pr: change existing extension

#2142 Xeltalliv/clippingblending: Fix canvas alpha compatibility and other changes
  extensions/Xeltalliv/clippingblending.js
Labels: pr: change existing extension, javascript

#2153 SharkPool/Camera: improve performance after many drawables created and deleted
  extensions/SharkPool/Camera.js
Labels: pr: change existing extension

#2167 [Automated] Update translations 2025-06-14
  translations/extension-metadata.json
  translations/extension-runtime.json
Labels: pr: other

#2172 Lily/ListTools: Fix 'repeat x times in list' only adding to extractor list
  extensions/Lily/ListTools.js
Labels: pr: change existing extension

#2175 [Automated] Update translations 2025-06-21
  translations/extension-metadata.json
  translations/extension-runtime.json
Labels: pr: other

#2180 [Automated] Update translations 2025-06-25
  translations/extension-runtime.json
Labels: pr: other
